Ecogo_2025/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acceso.urls')),
    path('home/', include('home.urls')),
    path('alumno/', include('alumno.urls')),
    path('docente/', include('docente.urls')),
    path('coordinador/', include('coordinador.urls')),
    #path('inventario/', include('inventario.urls')),
    #path('core/', include('core.urls')),

    path("__reload__/", include("django_browser_reload.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

coordinador/urls.py
from django.urls import path
from .views import *

app_name = 'coordinador'

urlpatterns = [
    #home coordinador
    path('',home_coordinador , name='home_coordinador'),
    #usuarios
    path('crear-usuario/', crear_usuario, name='crear-usuario'),
    path('editar-usuario/<int:id>/', editar_usuario, name='editar-usuarios'),
    path('listar-usuario/', listar_usuario, name='listar-usuario'),
    path('lista-usuarios/', lista_usuarios, name='lista-usuarios'), 
    #Gestionar salidas
    path('listar-salida/', listar_salida, name="listar_salida"),
    path('crear-salida/', crear_salida, name="crear_salida"),
    path('editar-salida/<int:id>/', editar_salida, name="editar_salida"),
    path('eliminar-salida/<int:id>/', eliminar_salida, name="eliminar_salida"),
    path('obtener-secciones/', obtener_secciones, name='obtener_secciones'),
    path('msj-wsp/', crear_grupo_wsp, name='crear_grupo_wsp'),
    #Gestionar alumnos
    #path('listar-alumno/', listar_alumno, name="listar_alumno"),

    #gestionar asignaturas
    path('listar-asignatura/', listar_asignatura, name="listar_asignatura"),
    path('crear-asignatura/', crear_asignatura, name="crear_asignatura"),
    path('editar-asignatura/<int:id>/', editar_asignatura, name="editar_asignatura"),
    path('eliminar-asignatura/<int:id>/', eliminar_asignatura, name="eliminar_asignatura"),
    

]

core/urls.py
from django.urls import path
from .views import *

from django.conf.urls import handler403
from .views import error_403_view

handler403 = error_403_view


urlpatterns = [
    path('403/', error_403_view, name='403'),
    

]

coordinador/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from core.models import *

class DiaSemana(models.Model):
    nombre = models.CharField(max_length=100)

# Definir los choices para los campos que los requieren
SEMAFORO_CHOICES = [
    ('verde', 'Confirmado'),
    ('amarillo', 'Viable'),
    ('rojo', 'Poco fiable'),
    ('gris', 'Por confirmar'),
]

EXP_APRENDIZAJE_CHOICES = [
    ('EA-1', 'EA-1'),
    ('EA-2', 'EA-2'),
    ('EA-3', 'EA-3'),
    ('EA-4', 'EA-4'),
    ('examen_transversal', 'Examen Transversal'),
    ('por_definir', 'Por definir'),  # Se agrega por defecto
]

ACTIVIDAD_CHOICES = [
    ('actividad_1', 'Actividad 1'),
    ('actividad_2', 'Actividad 2'),
    ('actividad_3', 'Actividad 3'),
    ('actividad_4', 'Actividad 4'),
    ('por_definir', 'Por definir'),  # Se agrega por defecto
]

ESTADO_CHOICES = [
    ('EJECUTADO', 'Ejecutado'),
    ('POR_EJECUTAR', 'Por Ejecutar'),
    ('SUSPENDIDO', 'Suspendido'),
    ('por_definir', 'Por definir'),  # Se agrega por defecto

]

SEMESTRE_CHOICES = [
    (1, '1 Semestre'),
    (2, '2 Semestre'),
    (3, '3 Semestre'),
    (4, '4 Semestre'),
    (5, '5 Semestre'),
    (6, '6 Semestre'),
    (7, '7 Semestre'),
    (8, '8 Semestre'),
]

class SalidaTerreno(models.Model):
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='por_definir')  # Default agregado
    activo = models.BooleanField(default=True)  # Campo booleano para activar/desactivar
    numero_cuenta = models.IntegerField(validators=[MaxValueValidator(9999999999)], blank=True, null=True)
    semestre = models.IntegerField(choices=SEMESTRE_CHOICES, blank=True, null=True)
    anio = models.PositiveIntegerField(validators=[MaxValueValidator(3000)], blank=True, null=True)
    semana = models.PositiveIntegerField(validators=[MaxValueValidator(3000)], blank=True, null=True)
    diasemana = models.ManyToManyField(DiaSemana, blank=True)
    actividad = models.CharField(max_length=200, blank=True, null=True, default='por_definir')
    fecha_ingreso = models.DateField()
    fecha_termino = models.DateField()
    dias = models.PositiveIntegerField(validators=[MaxValueValidator(99)], blank=True, null=True, default=0) 
    noches = models.PositiveIntegerField(validators=[MaxValueValidator(99)],blank=True, null=True, default=0)
    lugar_ejecucion = models.CharField(max_length=60)
    asignaturas = models.ManyToManyField(Asignatura, related_name='salidas_terreno', blank=True)
    exp_aprendizaje = models.CharField(max_length=20, choices=EXP_APRENDIZAJE_CHOICES, blank=True, null=True, default='por_definir')
    secciones = models.ManyToManyField(Seccion, blank=True)
    docente_reemplazo  = models.OneToOneField(UsersMetadata, related_name='salidas_terreno_apoyo_reemplazo', blank=True, null=True, on_delete=models.SET_NULL)#
    # docentes_apoyo2 = models.OneToOneField(UsersMetadata, related_name='salidas_terreno_apoyo2', blank=True, null=True, on_delete=models.SET_NULL)#
    # docentes_apoyo3 = models.OneToOneField(UsersMetadata, related_name='salidas_terreno_apoyo3', blank=True, null=True, on_delete=models.SET_NULL)#
    # docentes_apoyo4 = models.OneToOneField(UsersMetadata, related_name='salidas_terreno_apoyo4', blank=True, null=True, on_delete=models.SET_NULL)#
    docentes_apoyo = models.ManyToManyField(UsersMetadata, related_name='salidas_terreno_apoyo', blank=True)
    num_salida = models.CharField(max_length=30, choices=[(str(i), str(i)) for i in range(1, 5)] + [('no_requiere', 'No Requiere')], blank=True, null=True)
    observaciones = models.TextField(blank=True, null=True)
    semaforo = models.CharField(max_length=20, choices=SEMAFORO_CHOICES, blank=True, null=True)
    totalhoras = models.PositiveIntegerField(validators=[MaxValueValidator(99)], blank=True, null=True, default=0)#
    linkmapa = models.URLField(max_length=200, blank=True, null=True)#
    iframe_html = models.TextField(blank=True, null=True)#
    cantidad_alumnos = models.PositiveIntegerField(validators=[MaxValueValidator(99)], blank=True, null=True, default=0)#
    proveedor_sugerido = models.CharField(max_length=100, blank=True, null=True)#
    nro_oc_transporte = models.CharField(max_length=100, blank=True, null=True)#
    proveedor_transporte = models.CharField(max_length=100, blank=True, null=True)#
    valor_transporte = models.PositiveIntegerField(validators=[MaxValueValidator(9999999)], blank=True, null=True, default=0)#
    proveedor_servicios = models.CharField(max_length=100, blank=True, null=True, default='No Aplica')#
    nro_oc_servicios = models.CharField(max_length=100, blank=True, null=True, default='No Aplica')#
    valor_servicios = models.PositiveIntegerField(validators=[MaxValueValidator(9999999)], blank=True, null=True, default=0)#
    observaciones_programacion = models.TextField(blank=True, null=True)#
    docente_responsable_doc  = models.OneToOneField(UsersMetadata, related_name='salidas_terreno_docente_responsable', blank=True, null=True, on_delete=models.SET_NULL)#








    

    def __str__(self):
        asignaturas_str = ', '.join([asignatura.nombre for asignatura in self.asignaturas.all()])
        return f"Salida a terreno de {asignaturas_str} - {self.fecha_ingreso}"
    
    def asignaturas_x_seccion(self):
        """
        Retorna un diccionario con las asignaturas y la cantidad de secciones asociadas a este viaje.
        """
        from django.db.models import Count

        try:
            asignaturas_secciones = self.secciones.values('asignatura__nombre').annotate(total_secciones=Count('id'))
            data = {item['asignatura__nombre']: item['total_secciones'] for item in asignaturas_secciones}

            # Agregar asignaturas sin secciones
            asignaturas_sin_secciones = self.asignaturas.exclude(nombre__in=data.keys())
            for asignatura in asignaturas_sin_secciones:
                data[asignatura.nombre] = 'Sin secciones asignadas'

            # Verificar secciones sin asignaturas
            secciones_sin_asignaturas = self.secciones.filter(asignatura__isnull=True)
            if secciones_sin_asignaturas.exists():
                data['Secciones sin asignatura'] = 'Existen secciones sin asignatura asignada'

            return data
        except Exception as e:
            # Log the exception if needed
            return {}

    def get_asignaturas_secciones_list(self):
        """
        Retorna una lista de tuplas con las asignaturas y la cantidad de secciones asociadas a este viaje.
        """
        try:
            data = self.asignaturas_x_seccion()
            return [(asignatura, total_secciones) for asignatura, total_secciones in data.items()]
        except Exception as e:
            # Log the exception if needed
            return []


    class Meta:
        verbose_name = 'Salida Terreno'
        verbose_name_plural = 'Salidas Terreno'

templates/coordinador/asignaturas/crear_asignatura.html
{% extends '../../layout/index_C.html' %}
{% load static %}
{% block content %}
{% load tailwind_filters %}



<div class="mb-4 flex items-center">
    <a href="{% url 'coordinador:home_coordinador' %}" class="btn btn-secondary flex items-center">
        <img src="{% static 'botones/barrow.svg' %}" alt="Volver" class="h-20 mr-2">
        <h2 class="mi-h2 mx-auto text-center -mt-5">Volver</h2>
    </a>


</div>


<div class="mb-4  ">
      
    <h1 class="mx-auto mi-h1 text-center">Crear Asignatura</h1>
    </div>





<form class="px-10 font-semibold " method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    <!-- Formulario para crear usuario -->

    <div class="card mb-4 borde-trazo-5 pt-2 text-cuscol2">
        <div class="card-header font-semibold p-4">Información General</div>
        <div class="card-body p-4">
            <div class="space-y-4">
                <div>
                    <label class="block text-sm font-medium text-gray-700">Nombre de la Asignatura</label>
                    {{ form.nombre|as_crispy_field  }}
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700">Sigla</label>
                    {{ form.sigla|as_crispy_field  }}
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700">Coordinador</label>
                    {{ form.coordinador|as_crispy_field  }}
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700">Semestre</label>
                    {{ form.semestre|as_crispy_field  }}
                </div>
            </div>

           
        </div>
    </div>

    <div class="relative flex justify-center py-10">
                    
        <button type="submit" class="bg-cuscol4 rounded-3xl boton sombra  border-4 border-cuscol2 text-cuscol2 font-extrabold text-lg py-2 px-4 w-3/4 relative">Crear</button>
    </div>
  
      <!-- Botón para enviar el formulario -->
      
    </form>

{% endblock %}

templates/coordinador/asignaturas/editar_asignatura.html
{% extends '../../layout/index_C.html' %}
{% load static %}
{% block content %}
{% load tailwind_filters %}



<div class="mb-4 flex items-center">
    <a href="{% url 'coordinador:home_coordinador' %}" class="btn btn-secondary flex items-center">
        <img src="{% static 'botones/barrow.svg' %}" alt="Volver" class="h-20 mr-2">
        <h2 class="mi-h2 mx-auto text-center -mt-5">Volver</h2>
    </a>


</div>








<form class="px-10 font-semibold " method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    <!-- Formulario para crear usuario -->

    <div class="card mb-4 borde-trazo-5 pt-0 text-cuscol2 sombra">
        <h1 class="mx-auto border-0  rounded-t-2xl mi-h2 text-center bg-cuscol2 text-white">Editar Asignatura</h1>
        <div class="card-body p-4">
            <div class="space-y-4">
                <div>
                    <label class="block text-sm font-medium text-gray-700">Nombre de la Asignatura</label>
                    {{ form.nombre|as_crispy_field  }}
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700">Sigla</label>
                    {{ form.sigla|as_crispy_field  }}
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700">Coordinador</label>
                    {{ form.coordinador|as_crispy_field  }}
                </div>

                <div>
                    <label class="block text-sm font-medium text-gray-700">Semestre</label>
                    {{ form.semestre|as_crispy_field  }}
                </div>
            </div>
            <div class="relative flex justify-center py-10">
                    
                <button type="submit" class="bg-cuscol4 boton sombra  borde-trazo-5 text-cuscol2 font-extrabold text-lg py-2 px-4 w-3/4 relative">Editar</button>
            </div>
           
        </div>
    </div>

      <!-- Botón para enviar el formulario -->
      
    </form>













 <!-- Secciones -->



    <div class="py-36 px-5p">
        <h2 class="font-bold mb-4 mi-h2 pb-5">Secciones</h2>
        
        <div x-data="{ activeTab: 0 }">
            <!-- Tabs -->
            <ul class="flex items-center">
                {% for seccion in secciones %}
                    <li>
                        <button 
                            @click="activeTab = {{ forloop.counter0 }}" 
                            :class="{ 'texto-azul borde-filtro-1 py-2 ': activeTab === {{ forloop.counter0 }} }"
                            class="px-4 py-2 texto-azul"
                        >
                            {{ seccion.nombre }}
                        </button>
                    </li>
                {% endfor %}
            </ul>
            
            <!-- Tab Content -->
            <div class="p-4 borde-filtro-2">
                {% for seccion in secciones %}
                    <div x-show="activeTab === {{ forloop.counter0 }}" class="p-4">
                        <h3 class="text-lg font-bold pb-3">Detalles de la Sección</h3>
                        <p><strong>Docente:</strong> {{ seccion.docente.usersmetadata.nombres }} {{ seccion.docente.usersmetadata.ap_paterno }}</p>
                        <p><strong>Cupo:</strong> {{ seccion.cupo }}</p>
                        <p><strong>Espacios disponibles:</strong> {{ seccion.espacios_disponibles }}</p>
                        
                        <div class="mt-4">
                            <a href="" class="bg-green-500 hover:bg-green-600 text-white py-2 px-4 rounded mr-2">
                                Editar
                            </a>
                            <a href="" class="bg-red-500 hover:bg-red-600 text-white py-2 px-4 rounded">
                                Eliminar
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>



    

{% endblock %}

templates/coordinador/asignaturas/listar_asignatura.html
{% extends '../../layout/index_C.html' %}
{% load static %}
{% block content %}
{% load tailwind_filters %}




<div class="mb-4 flex items-center">
    <a href="{% url 'coordinador:home_coordinador' %}" class="btn btn-secondary flex items-center">
        <img src="{% static 'botones/barrow.svg' %}" alt="Volver" class="h-20 mr-2">
        <h2 class="mi-h2 mx-auto text-center -mt-5">Volver</h2>
    </a>
</div>








<h1 class=" py-10 sm:text-5xl mb-4 md:mb-0 text-center mi-h1 md:text-center w-full md:w-auto">Gestion de Asignaturas</h1>

<div class="mb-4 flex flex-col items-center md:flex-row md:items-center md:justify-between px-4">




   
    
    <div class="md:ml-auto">
        <a href="{% url 'coordinador:crear_asignatura' %}" class="boton borde-trazo-3 px-6 py-2 texto-parrafo">Agregar nueva Asignatura
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline-block ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
            </svg>
        </a>
    </div>
</div>





<!-- Responsive table -->
<div class="container  py-10 mx-auto">
    <!-- Acordeón: Todas las Asignaturas -->
    <div class="mb-8 md:-mx-28 border border-gray-200 rounded-2xl shadow-md">
        <button class="w-full bg-cuscol2 text-white text-center px-4 py-2 text-3xl font-bold rounded-t-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                onclick="toggleAccordion('todas-asignaturas')">
            Todas las Asignaturas
        </button>
        <div class="flex">
            <div class="w-1/3 h-5 bg-cuscol1 rounded-bl-2xl"></div>
            <div class="w-2/3 h-5 bg-cuscol3 rounded-br-2xl"></div>
        </div>
        <div id="todas-asignaturas" class="hidden">
            <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4">
                {% for asignatura in asignaturas %}
                <div class="bg-white shadow-md rounded-lg p-4 border border-gray-300 hover:border-gray-400">
                    <h3 class="text-lg font-semibold text-gray-800 line-clamp-2">{{ asignatura.nombre }}</h3>
                    <p class="text-sm text-gray-600">Sigla: {{ asignatura.sigla }}</p>
                    <p class="text-sm text-gray-600">Semestre: {{ asignatura.get_semestre_display }}</p>
                    <p class="text-sm text-gray-600">Coordinador: 
                        {{ asignatura.coordinador.usersmetadata.nombres }}
                        {{ asignatura.coordinador.usersmetadata.ap_paterno }}
                        {{ asignatura.coordinador.usersmetadata.ap_materno }}
                    </p>
                    <div class="mt-4 mx-2 flex justify-between sm:flex-col">
                        <a href="{% url 'coordinador:editar_asignatura' asignatura.id %}" class="boton borde-trazo-3 mb-2 px-6 py-2 text-sm sm:text-base flex items-center justify-center">Editar</a>
                        <a href="{% url 'coordinador:eliminar_asignatura' asignatura.id %}" class="bg-gray-400 hover:bg-cuscol2 text-white borde-trazo-3 px-6 py-2 text-sm sm:text-base flex items-center justify-center">Eliminar</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    

    <!-- Acordeón: Asignaturas por semestre -->
    <div>
        {% for semestre, asignaturas_semestre in asignaturas_por_semestre.items %}
        <div class="mb-4 md:-mx-28  border  border-gray-300 rounded-2xl shadow-md   hover:border-gray-400">
            <button class="w-full bg-cuscol2 text-white text-center px-0 py-2 text-3xl font-bold rounded-t-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    onclick="toggleAccordion('semestre-{{ semestre }}')">
                Semestre {{ semestre }}
                
            </button>
            <div class="flex ">
                <div class="w-1/3 h-5 bg-cuscol1 rounded-bl-2xl"></div>
                <div class="w-2/3 h-5 bg-cuscol3 rounded-br-2xl"></div>
            </div>
            <div id="semestre-{{ semestre }}" class="hidden">
                <div class="p-4 ">
                    {% for asignatura in asignaturas_semestre %}
                    <div class="bg-white shadow-md rounded-lg p-4 mb-4 flex flex-col sm:flex-row sm:items-center sm:justify-between border  border-gray-300 hover:border-gray-500 ">
                        <div class="">
                            <h3 class="text-lg font-semibold text-gray-800">{{ asignatura.nombre }}</h3>
                            <p class="text-sm text-gray-600">Sigla: {{ asignatura.sigla }}</p>
                            <p class="text-sm text-gray-600">Coordinador: 
                                {{ asignatura.coordinador.usersmetadata.nombres }}
                                {{ asignatura.coordinador.usersmetadata.ap_paterno }}
                                {{ asignatura.coordinador.usersmetadata.ap_materno }}
                            </p>
                        </div>
                        <div class="mt-4 sm:mt-0 flex flex-col sm:flex-row sm:space-x-2">
                            <a href="{% url 'coordinador:editar_asignatura' asignatura.id %}" class="boton borde-trazo-3 px-6 py-2 mb-2 text-sm sm:text-base flex items-center justify-center">Editar</a>
                            <a href="{% url 'coordinador:eliminar_asignatura' asignatura.id %}" class="boton hover:bg-cuscol2 hover:text-white bg-gray-400 text-white borde-trazo-3 px-6 py-2 mb-2 text-sm sm:text-base flex items-center justify-center">Eliminar</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    // Función para mostrar/ocultar contenido del acordeón
    function toggleAccordion(id) {
        const element = document.getElementById(id);
        if (element.classList.contains('hidden')) {
            element.classList.remove('hidden');
        } else {
            element.classList.add('hidden');
        }
    }
</script>



<script>
  // Configurar el Toast
  const Toast = Swal.mixin({
    toast: true,
    position: "top-end",
    showConfirmButton: false,
    timer: 3000,
    timerProgressBar: true,
    didOpen: (toast) => {
      toast.addEventListener("mouseenter", Swal.stopTimer);
      toast.addEventListener("mouseleave", Swal.resumeTimer);
    }
  });

  // Mostrar mensajes de Django en Toast
  {% if messages %}
  {% for message in messages %}
    Toast.fire({
      icon: "{% if message.tags == 'success' %}success{% elif message.tags == 'error' %}error{% else %}info{% endif %}",
      title: "{{ message }}"
    });
  {% endfor %}
  {% endif %}

  // Evento para el botón manual (prueba)
  document.getElementById("show-toast").addEventListener("click", () => {
    Toast.fire({
      icon: "success",
      title: "¡Este es un Toast de prueba!"
    });
  });
</script>


<script>
    function confirmDelete(id, url) {
        Swal.fire({
            html: `
                <div class="bg-white my-2 dark:bg-white  borde-trazo-5 sombra my-5">
                    <h2 class="bg-cuscol2 text-white text-center py-3 ">¿Estás seguro?</h2>
                            <button type="button" id="confirmNo" class="modal-close absolute top-6 end-16 text-white bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-cuscol1 dark:hover:text-white">
                        <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                        </svg>
                        <span class="sr-only">Close modal</span>
                    </button> 
                    <img src="{% static 'images/elementos gráficos/signo-exclamacion.png' %}" alt="404" class=" mx-auto py-5" />
                    <p class="text-gray-600 mt-2 bg-white ">La salida <strong>${id}</strong> será eliminada.</p>
                    <p class="text-gray-600 mt-2 bg-white ">Esta acción no se puede deshacer</p>
                    <div class="flex justify-center my-4 ">
                    


                        <button id="confirmYes" class="w-full mx-4 sm:w-auto boton borde-trazo-3 px-5 text-sm font-medium py-2.5">
                            <p>Confirmar</p>
                        </button>
                        <button id="confirmNo" class="w-full sm:w-auto rounded-xl bg-gray-400 hover:bg-cuscol2 text-white borde-trazo-3 text-sm font-medium px-5 py-2.5 hover:text-white">
                            <p>Cancelar</p>
                        </button>
                    </div>
                </div>
            `,
            showConfirmButton: false,
            customClass: {
                popup: 'bg-transparent shadow-none',
                container: 'bg-black bg-opacity-50 backdrop-blur-md',
            },
            didRender: () => {
                document.getElementById('confirmYes').addEventListener('click', () => {
                    window.location.href = url; // Redirige a la URL de eliminación
                });
                document.getElementById('confirmNo').addEventListener('click', () => {
                    Swal.close(); // Cierra el SweetAlert
                });
            }
        });
    }

</script>


    
{% endblock %}