Ecogo_2025/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acceso.urls')),
    path('home/', include('home.urls')),
    path('alumno/', include('alumno.urls')),
    path('docente/', include('docente.urls')),
    path('coordinador/', include('coordinador.urls')),
    #path('inventario/', include('inventario.urls')),
    #path('core/', include('core.urls')),

    path("__reload__/", include("django_browser_reload.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

coordinador/urls.py
from django.urls import path
from .views import *

app_name = 'coordinador'

urlpatterns = [
    #home coordinador
    path('',home_coordinador , name='home_coordinador'),
    #usuarios
    path('crear-usuario/', crear_usuario, name='crear-usuario'),
    path('editar-usuario/<int:id>/', editar_usuario, name='editar-usuarios'),
    path('listar-usuario/', listar_usuario, name='listar-usuario'),
    path('lista-usuarios/', lista_usuarios, name='lista-usuarios'), 
    #Gestionar salidas
    path('listar-salida/', listar_salida, name="listar_salida"),
    path('crear-salida/', crear_salida, name="crear_salida"),
    path('editar-salida/<int:id>/', editar_salida, name="editar_salida"),
    path('eliminar-salida/<int:id>/', eliminar_salida, name="eliminar_salida"),
    path('obtener-secciones/', obtener_secciones, name='obtener_secciones'),
    path('msj-wsp/', crear_grupo_wsp, name='crear_grupo_wsp'),
    #Gestionar alumnos
    #path('listar-alumno/', listar_alumno, name="listar_alumno"),

    #gestionar asignaturas
    path('listar-asignatura/', listar_asignatura, name="listar_asignatura"),
    path('crear-asignatura/', crear_asignatura, name="crear_asignatura"),
    path('editar-asignatura/<int:id>/', editar_asignatura, name="editar_asignatura"),
    path('eliminar-asignatura/<int:id>/', eliminar_asignatura, name="eliminar_asignatura"),
    

]

core/urls.py
from django.urls import path
from .views import *

from django.conf.urls import handler403
from .views import error_403_view

handler403 = error_403_view


urlpatterns = [
    path('403/', error_403_view, name='403'),
    

]

templates/layout/index.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="es-CL">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Sitio Web{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style_wally.css' %}">
    <link rel="stylesheet" href="{% static 'css/tailwind/styles.css' %}">
    
    
    {% tailwind_css %}
</head>
<body>

    
    
        {% block content %}
        <!-- Contenido principal -->
        {% endblock %}
    
    
    
    
</body>
</html>

templates/layout/index_A.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="es-CL">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Sitio Web{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style_wally.css' %}">
    <link rel="stylesheet" href="{% static 'css/tailwind/styles.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
    {% tailwind_css %}
</head>
<body>

   

  <!-- Navbar -->
  <nav class="bg-azul">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto py-3">
        <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="{% static 'images/EcoGo_logo pequeño.png' %}" class="h-10 sm:h-16" alt="ecogo Logo" />
           
        </a>
        <span class="text-center mi-h2 text-cuscol4  dark:text-cuscol4">Alumnos</span>
        <button id="menu-toggle" class="inline-flex items-center justify-center p-2 w-10 h-10 text-sm text-gray-500 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="drawer-disabled-backdrop">
            <span class="sr-only">Menu</span>
            <svg class=" h-12 text-cuscol4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 22 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 1h12M1 7h18M4 13h12"/>
            </svg>
        </button>
    </div>
</nav>

<!-- Drawer Component -->
<div id="drawer-disabled-backdrop" class=" fixed top-0 left-0 z-40 h-screen  p-4 overflow-y-auto transition-transform -translate-x-full bg-white w-64 sm:w-2/6 dark:text-cuscol4" tabindex="-1" aria-labelledby="drawer-disabled-backdrop-label">
    <div class="relative">
        <img src="{% static 'images/elementos gráficos/esquina-eco.webp' %}" alt="Imagen" class="absolute -bottom-24 -left-4 h-32 w-32 object-contain ">
        
    </div><h5 id="drawer-disabled-backdrop-label" class="text-base mt-20 ml-5 font-semibold text-cuscol2 uppercase dark:text-cuscol2">Bienvenido: <span class="text-cuscol2  font-extrabold" > Matías Sebastian Inayao Poveda</span></h5>
    <button id="close-drawer" type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 absolute top-2.5 end-2.5 inline-flex items-center justify-center dark:hover:bg-cuscol1 dark:hover:text-white">
        <svg class="w-3 h-3 text-cuscol2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
        <span class="sr-only">Close menu</span>
    </button>
    <div class="py-4 overflow-y-auto">
        <ul class="space-y-2 font-medium">
            <li>
                <a href="#" class="flex items-center p-2 text-cuscol2 rounded-lg dark:text-cuscol2 hover:bg-cuscol1 dark:hover:bg-cuscol1 group">
                    <svg class="w-5 h-5 text-text-cuscol2 transition duration-75 dark:text-cuscol2 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M11.47 3.84a.75.75 0 011.06 0l8.69 8.69a.75.75 0 101.06-1.06l-8.689-8.69a2.25 2.25 0 00-3.182 0l-8.69 8.69a.75.75 0 001.061 1.06l8.69-8.69z" />
                        <path d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" />
                    </svg>
                    <span class="ms-3">Inicio</span>
                </a>
            </li>
            <li>
                <a href="#" class="flex items-center p-2 text-cuscol2 rounded-lg dark:text-cuscol2 hover:bg-cuscol1 dark:hover:bg-cuscol1 group">
                    <svg class="w-5 h-5 text-cuscol2 transition duration-75 dark:text-cuscol2 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M11.47 3.84a.75.75 0 011.06 0l8.69 8.69a.75.75 0 101.06-1.06l-8.689-8.69a2.25 2.25 0 00-3.182 0l-8.69 8.69a.75.75 0 001.061 1.06l8.69-8.69z" />
                        <path d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" />
                    </svg>
                    <span class="ms-3 ">Mis Salidas</span>
                </a>
            </li>
            <li>
                <button type="button" class="flex items-center w-full p-2 text-base text-cuscol2 transition duration-75 rounded-lg group hover:bg-cuscol1 dark:text-cuscol2 dark:hover:bg-cuscol1" aria-controls="dropdown-example" data-collapse-toggle="dropdown-example">
                      <svg class="flex-shrink-0 w-5 h-5 text-cuscol2 transition duration-75 group-hover:text-gray-900 dark:text-cuscol2 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M11.983 1.5a1.5 1.5 0 0 1 1.5 1.5v.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1.5h.5a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-.5v1.5a1.5 1.5 0 0 1-1.5 1.5h-1.5v.5a1.5 1.5 0 0 1-1.5 1.5h-3a1.5 1.5 0 0 1-1.5-1.5v-.5H6.5a1.5 1.5 0 0 1-1.5-1.5v-1.5h-.5a1.5 1.5 0 0 1-1.5-1.5v-3a1.5 1.5 0 0 1 1.5-1.5h.5V4.5a1.5 1.5 0 0 1 1.5-1.5h1.5v-.5a1.5 1.5 0 0 1 1.5-1.5h3zm-1.5 4a3 3 0 1 0 0 6 3 3 0 0 0 0-6z"/>
                      </svg>
                      <span class="flex-1 ms-3 text-left rtl:text-right whitespace-nowrap">Configuraciones</span>
                      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                         <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                      </svg>
                </button>
                <ul id="dropdown-example" class="hidden py-2 space-y-2 ">
                      <li>
                         <a href="#" class="flex items-center w-full p-2 text-cuscol2 transition duration-75 rounded-lg pl-11 group hover:bg-cuscol1 dark:text-cuscol2 dark:hover:bg-cuscol1">Perfil</a>
                      </li>
                      <li>
                         <a href="#" class="flex items-center w-full p-2 text-cuscol2 transition duration-75 rounded-lg pl-11 group hover:bg-cuscol1 dark:text-cuscol2 dark:hover:bg-cuscol1">Cambio de Contraseña</a>
                      </li>
                      
                </ul>
             </li>

             <li class="pt-32">
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="flex items-center p-2 text-white bg-red-600 rounded-2xl w-3/4 py-3 mx-auto hover:bg-red-700 dark:bg-red-600 dark:hover:bg-red-700 group">
                        <svg class="w-5 h-5 text-white transition duration-75 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                            <path d="M16 13v-2H7V8l-5 4 5 4v-3h9zM20 3H4c-1.1 0-2 .9-2 2v4h2V5h16v14H4v-4H2v4c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z"/>
                        </svg>
                        <span class="ms-3">Cerrar Sesión</span>
                    </button>
                </form>
            {% endif %}
            </li>
           







            <!-- Add more menu items here -->
        </ul>
    </div>
</div>

<!-- JavaScript -->
<script>
    const drawer = document.getElementById("drawer-disabled-backdrop");
    const toggleButton = document.getElementById("menu-toggle");
    const closeButton = document.getElementById("close-drawer");

    toggleButton.addEventListener("click", () => {
        drawer.classList.toggle("-translate-x-full");
    });

    closeButton.addEventListener("click", () => {
        drawer.classList.add("-translate-x-full");
    });
</script>





    
    <main>
        {% block content %}
        <!-- Contenido principal -->
        {% endblock %}
    </main>
    
    <footer class=" fixed bottom-0 left-0 w-full text-cuscol4 bg-cuscol2 ">
        <div class="relative">
            <img src="{% static 'images/elementos gráficos/esquina-eco.webp' %}" alt="Imagen" class="absolute bottom-0 left-0 h-full w-auto object-contain md:h-full">
            <p class="text-sm text-center py-4">&copy; 2024-2025 EcoGo. Todos los derechos reservados.</p>
        </div>
    </footer>  
    
</body>
</html>

templates/layout/index_C.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="es-CL">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Sitio Web{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style_wally.css' %}">
    <link rel="stylesheet" href="{% static 'css/tailwind/styles.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
    <link rel="stylesheet" href="{% static 'salert/dist/sweetalert2.min.css' %}">
    <script src="{% static 'salert/dist/sweetalert2.min.js' %}" ></script>

    
    {% tailwind_css %}
</head>
<body>

   

  <!-- Navbar -->
  <nav class="bg-azul">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto py-3">
        <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="{% static 'images/EcoGo_logo pequeño.png' %}" class="h-10 sm:h-16" alt="ecogo Logo" />
           
        </a>
        <span class="text-center mi-h2 text-cuscol4  dark:text-cuscol4">Coordinadores</span>
        <button id="menu-toggle" class="inline-flex items-center justify-center p-2 w-10 h-10 text-sm text-gray-500 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="drawer-disabled-backdrop">
            <span class="sr-only">Menu</span>
            <svg class=" h-12 text-cuscol4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 22 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 1h12M1 7h18M4 13h12"/>
            </svg>
        </button>
    </div>
</nav>

<!-- Drawer Component -->
<div id="drawer-disabled-backdrop" class=" fixed top-0 left-0 z-40 h-screen  p-4 overflow-y-auto transition-transform -translate-x-full bg-white w-64 sm:w-2/6 dark:text-cuscol4" tabindex="-1" aria-labelledby="drawer-disabled-backdrop-label">
    <div class="relative">
        <img src="{% static 'images/elementos gráficos/esquina-eco.webp' %}" alt="Imagen" class="absolute -bottom-24 -left-4 h-32 w-32 object-contain ">
        
    </div>
    <h5 id="drawer-disabled-backdrop-label" class="text-base mt-20 ml-5 font-semibold text-cuscol2 uppercase dark:text-cuscol2">Bienvenido: <span class="text-cuscol2  font-extrabold" > {{user.usersmetadata.nombres}} {{user.usersmetadata.ap_paterno}} {{user.usersmetadata.ap_materno}}</span></h5>
    <button id="close-drawer" type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 absolute top-2.5 end-2.5 inline-flex items-center justify-center dark:hover:bg-cuscol1 dark:hover:text-white">
        <svg class="w-3 h-3 text-cuscol2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
        
            
            
        
        <span class="sr-only">Close menu</span>
    </button>
    <div class="py-5 overflow-y-auto">
        
        <ul class="space-y-2 font-medium">
            <li>
                <a href="{% url 'coordinador:home_coordinador' %} " class="flex items-center p-2 text-cuscol2 rounded-lg dark:text-cuscol2 hover:bg-cuscol1 dark:hover:bg-cuscol1 group">
                    <svg class="w-5 h-5 text-text-cuscol2 transition duration-75 dark:text-cuscol2 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M11.47 3.84a.75.75 0 011.06 0l8.69 8.69a.75.75 0 101.06-1.06l-8.689-8.69a2.25 2.25 0 00-3.182 0l-8.69 8.69a.75.75 0 001.061 1.06l8.69-8.69z" />
                        <path d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" />
                    </svg>
                    <span class="ms-3">Inicio</span>
                </a>
            </li>
            <li>
                <a href="{% url 'coordinador:listar_salida' %}" class="flex items-center p-2 text-cuscol2 rounded-lg dark:text-cuscol2 hover:bg-cuscol1 dark:hover:bg-cuscol1 group">
                    <img src="{% static 'images/íconos/icono-salidas.webp' %}" class="w-5 h-8 transition duration-75 group-hover:text-gray-900" alt="Salidas icon">
                    <span class="ms-3 ">Gestionar salida a terreno</span>
                </a>
            </li>
            <li>
                <a href="{% url 'coordinador:listar_asignatura' %}" class="flex items-center p-2 text-cuscol2 rounded-lg dark:text-cuscol2 hover:bg-cuscol1 dark:hover:bg-cuscol1 group">
                    <svg class="w-5 h-5 text-cuscol2 transition duration-75 dark:text-cuscol2 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M11.47 3.84a.75.75 0 011.06 0l8.69 8.69a.75.75 0 101.06-1.06l-8.689-8.69a2.25 2.25 0 00-3.182 0l-8.69 8.69a.75.75 0 001.061 1.06l8.69-8.69z" />
                        <path d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" />
                    </svg>
                    <span class="ms-3 ">Gestionar asignaturas</span>
                </a>
            </li>
            <li>
                <a href="{% url 'coordinador:listar-usuario' %}" class="flex items-center p-2 text-cuscol2 rounded-lg dark:text-cuscol2 hover:bg-cuscol1 dark:hover:bg-cuscol1 group">
                    <svg class="w-5 h-5 text-cuscol2 transition duration-75 dark:text-cuscol2 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M11.47 3.84a.75.75 0 011.06 0l8.69 8.69a.75.75 0 101.06-1.06l-8.689-8.69a2.25 2.25 0 00-3.182 0l-8.69 8.69a.75.75 0 001.061 1.06l8.69-8.69z" />
                        <path d="M12 5.432l8.159 8.159c.03.03.06.058.091.086v6.198c0 1.035-.84 1.875-1.875 1.875H15a.75.75 0 01-.75-.75v-4.5a.75.75 0 00-.75-.75h-3a.75.75 0 00-.75.75V21a.75.75 0 01-.75.75H5.625a1.875 1.875 0 01-1.875-1.875v-6.198a2.29 2.29 0 00.091-.086L12 5.43z" />
                    </svg>
                    <span class="ms-3 ">Gestión Usuarios</span>
                </a>
            </li>
            
            <li>
                <button type="button" class="flex items-center w-full p-2 text-base text-cuscol2 transition duration-75 rounded-lg group hover:bg-cuscol1 dark:text-cuscol2 dark:hover:bg-cuscol1" aria-controls="dropdown-example" data-collapse-toggle="dropdown-example">
                      <svg class="flex-shrink-0 w-5 h-5 text-cuscol2 transition duration-75 group-hover:text-gray-900 dark:text-cuscol2 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M11.983 1.5a1.5 1.5 0 0 1 1.5 1.5v.5h1.5a1.5 1.5 0 0 1 1.5 1.5v1.5h.5a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-.5v1.5a1.5 1.5 0 0 1-1.5 1.5h-1.5v.5a1.5 1.5 0 0 1-1.5 1.5h-3a1.5 1.5 0 0 1-1.5-1.5v-.5H6.5a1.5 1.5 0 0 1-1.5-1.5v-1.5h-.5a1.5 1.5 0 0 1-1.5-1.5v-3a1.5 1.5 0 0 1 1.5-1.5h.5V4.5a1.5 1.5 0 0 1 1.5-1.5h1.5v-.5a1.5 1.5 0 0 1 1.5-1.5h3zm-1.5 4a3 3 0 1 0 0 6 3 3 0 0 0 0-6z"/>
                      </svg>
                      <span class="flex-1 ms-3 text-left rtl:text-right whitespace-nowrap">Cargas Masiva</span>
                      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                         <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                      </svg>
                </button>
                <ul id="dropdown-example" class="hidden py-2 space-y-2 ">
                      <li>
                         <a href="#" class="flex items-center w-full p-2 text-cuscol2 transition duration-75 rounded-lg pl-11 group hover:bg-cuscol1 dark:text-cuscol2 dark:hover:bg-cuscol1">Estudiantes</a>
                      </li>
                      <li>
                         <a href="#" class="flex items-center w-full p-2 text-cuscol2 transition duration-75 rounded-lg pl-11 group hover:bg-cuscol1 dark:text-cuscol2 dark:hover:bg-cuscol1">Asignaturas</a>
                      </li>
                      
                </ul>
             </li>

             <li class="pt-32">
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="flex items-center p-2 text-white bg-red-600 rounded-2xl w-3/4 py-3 mx-auto hover:bg-red-700 dark:bg-red-600 dark:hover:bg-red-700 group">
                        <svg class="w-5 h-5 text-white transition duration-75 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                            <path d="M16 13v-2H7V8l-5 4 5 4v-3h9zM20 3H4c-1.1 0-2 .9-2 2v4h2V5h16v14H4v-4H2v4c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z"/>
                        </svg>
                        <span class="ms-3">Cerrar Sesión</span>
                    </button>
                </form>
            {% endif %}
            </li>







            <!-- Add more menu items here -->
        </ul>
    </div>
</div>

<!-- JavaScript -->
<script>
    const drawer = document.getElementById("drawer-disabled-backdrop");
    const toggleButton = document.getElementById("menu-toggle");
    const closeButton = document.getElementById("close-drawer");

    toggleButton.addEventListener("click", () => {
        drawer.classList.toggle("-translate-x-full");
    });

    closeButton.addEventListener("click", () => {
        drawer.classList.add("-translate-x-full");
    });
</script>





    
    <main>
        {% block content %}
        <!-- Contenido principal -->
        {% endblock %}
    </main>
    
    <footer class=" fixed bottom-0 left-0 w-full text-cuscol4 bg-cuscol2 ">
        <div class="relative">
            <img src="{% static 'images/elementos gráficos/esquina-eco.webp' %}" alt="Imagen" class="absolute bottom-0 left-0 h-full w-auto object-contain md:h-full">
            <p class="text-sm text-center py-4">&copy; 2024-2025 EcoGo. Todos los derechos reservados.</p>
        </div>
    </footer>
    
</body>
</html>